name_list = ['Maria', 'João', 'Matheus']
print(name_list[0] + " would you like to have dinner at my house?")
print(name_list[1] + " would you like to have dinner at my house?")
print(name_list[2] + " would you like to have dinner at my house?")
print("I've found a bigger dinner table, now I have more guests to add to the list")
name_list.insert(0, 'Felipe')
name_list.insert(2, 'Pedro')
name_list.append('Gustavo')
print(name_list[0] + " would you like to have dinner at my house?")
print(name_list[1] + " would you like to have dinner at my house?")
print(name_list[2] + " would you like to have dinner at my house?")
print(name_list[3] + " would you like to have dinner at my house?")
print(name_list[4] + " would you like to have dinner at my house?")
print(name_list[5] + " would you like to have dinner at my house?")