places = ['Greece', 'Switzerland', 'Ireland', 'Japan', 'Canada', 'Spain', 'France']
print(places)
print("\nHere is the sorted list: ")
print(sorted(places))
print("\nHere is the original list: ")
print(places)
print("\nHere is the reverse sorted list: ")
print(sorted(places, reverse=True))
print("\nHere is the original list again: ")
print(places)
print("\nReversing list: ")
places.reverse()
print(places)
print("\nReversing list again: ")
places.reverse()
print(places)
print("\nSorting list in alphabetical order: ")
places.sort()
print(places)
print("\nSorting list in its reversed order: ")
places.sort(reverse=True)
print(places)